"""add_ultra_extraction_engine_tables

Revision ID: 467d1a296ab7
Revises: 8c9d0e1f2b3a
Create Date: 2026-01-18 20:40:21.267633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "467d1a296ab7"
down_revision: Union[str, Sequence[str], None] = "8c9d0e1f2b3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column(
            "sector",
            sa.Enum(
                "CLIENTS", "COMPANIES", "RECRUITERS", "CUSTOMERS", name="sectorenum"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="jobstatusenum",
            ),
            nullable=True,
        ),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("total_sources", sa.Integer(), nullable=True),
        sa.Column("processed_sources", sa.Integer(), nullable=True),
        sa.Column("total_records", sa.Integer(), nullable=True),
        sa.Column("success_count", sa.Integer(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.Column("duplicate_count", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("estimated_completion", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("result_file_path", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_jobs_candidate_id"),
        "extraction_jobs",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_jobs_id"), "extraction_jobs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_extraction_jobs_sector"), "extraction_jobs", ["sector"], unique=False
    )
    op.create_index(
        op.f("ix_extraction_jobs_status"), "extraction_jobs", ["status"], unique=False
    )
    op.create_table(
        "extraction_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "sector",
            sa.Enum(
                "CLIENTS", "COMPANIES", "RECRUITERS", "CUSTOMERS", name="sectorenum"
            ),
            nullable=False,
        ),
        sa.Column("filters", sa.JSON(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_templates_candidate_id"),
        "extraction_templates",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_templates_id"), "extraction_templates", ["id"], unique=False
    )
    op.create_table(
        "extraction_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "DISCOVERY",
                "FETCHING",
                "RENDERING",
                "PARSING",
                "ENRICHMENT",
                "VALIDATION",
                "STORAGE",
                name="extractionstageenum",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("current_source", sa.String(length=1000), nullable=True),
        sa.Column("current_layer", sa.Integer(), nullable=True),
        sa.Column("records_extracted", sa.Integer(), nullable=True),
        sa.Column("records_validated", sa.Integer(), nullable=True),
        sa.Column("errors_encountered", sa.Integer(), nullable=True),
        sa.Column("requests_made", sa.Integer(), nullable=True),
        sa.Column("bytes_downloaded", sa.Integer(), nullable=True),
        sa.Column("avg_response_time_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["extraction_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_progress_created_at"),
        "extraction_progress",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_progress_id"), "extraction_progress", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_extraction_progress_job_id"),
        "extraction_progress",
        ["job_id"],
        unique=False,
    )
    op.create_table(
        "extraction_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("extraction_layer", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("is_duplicate", sa.Boolean(), nullable=True),
        sa.Column("is_validated", sa.Boolean(), nullable=True),
        sa.Column("enriched_via_api", sa.Boolean(), nullable=True),
        sa.Column("api_source", sa.String(length=100), nullable=True),
        sa.Column("api_enrichment_data", sa.JSON(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["extraction_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_results_id"), "extraction_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_extraction_results_job_id"),
        "extraction_results",
        ["job_id"],
        unique=False,
    )

    # NOTE: Commented out drop operations for old tables from previous schema iterations.
    # These tables don't exist in fresh databases and were from an earlier version.
    # Uncomment only if you need to migrate from an old database with these tables.
    #
    # op.drop_index(op.f('ix_ab_tests_id'), table_name='ab_tests', if_exists=True)
    # op.drop_table('ab_tests', if_exists=True)
    # ... (other drop operations)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ab_test_assignments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("test_id", sa.INTEGER(), nullable=False),
        sa.Column("variant_id", sa.INTEGER(), nullable=False),
        sa.Column("campaign_id", sa.INTEGER(), nullable=False),
        sa.Column("assigned_at", sa.DATETIME(), nullable=True),
        sa.Column("assignment_method", sa.VARCHAR(length=50), nullable=True),
        sa.Column("has_reply", sa.BOOLEAN(), nullable=True),
        sa.Column("reply_received_at", sa.DATETIME(), nullable=True),
        sa.Column("emails_sent", sa.INTEGER(), nullable=True),
        sa.Column("emails_opened", sa.INTEGER(), nullable=True),
        sa.Column("time_to_reply_hours", sa.FLOAT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["follow_up_campaigns.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["test_id"], ["ab_tests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["ab_test_variants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", name=op.f("unique_campaign_assignment")),
    )
    op.create_index(
        op.f("ix_ab_test_assignments_variant_id"),
        "ab_test_assignments",
        ["variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ab_test_assignments_test_id"),
        "ab_test_assignments",
        ["test_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ab_test_assignments_id"), "ab_test_assignments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ab_test_assignments_campaign_id"),
        "ab_test_assignments",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ab_test_assignment_test_variant"),
        "ab_test_assignments",
        ["test_id", "variant_id"],
        unique=False,
    )
    op.create_table(
        "follow_up_emails",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("campaign_id", sa.INTEGER(), nullable=False),
        sa.Column("step_id", sa.INTEGER(), nullable=True),
        sa.Column("email_log_id", sa.INTEGER(), nullable=True),
        sa.Column("step_number", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=9), nullable=True),
        sa.Column("subject", sa.VARCHAR(length=500), nullable=False),
        sa.Column("body_text", sa.TEXT(), nullable=False),
        sa.Column("body_html", sa.TEXT(), nullable=True),
        sa.Column("is_auto_generated", sa.BOOLEAN(), nullable=True),
        sa.Column("is_user_edited", sa.BOOLEAN(), nullable=True),
        sa.Column("is_custom_written", sa.BOOLEAN(), nullable=True),
        sa.Column("original_subject", sa.VARCHAR(length=500), nullable=True),
        sa.Column("original_body", sa.TEXT(), nullable=True),
        sa.Column("strategy_used", sa.VARCHAR(length=18), nullable=True),
        sa.Column("tone_used", sa.VARCHAR(length=12), nullable=True),
        sa.Column("personalization_data", sqlite.JSON(), nullable=True),
        sa.Column("scheduled_for", sa.DATETIME(), nullable=True),
        sa.Column("timezone", sa.VARCHAR(length=50), nullable=True),
        sa.Column("sent_at", sa.DATETIME(), nullable=True),
        sa.Column("delivered_at", sa.DATETIME(), nullable=True),
        sa.Column("opened_at", sa.DATETIME(), nullable=True),
        sa.Column("clicked_at", sa.DATETIME(), nullable=True),
        sa.Column("replied_at", sa.DATETIME(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("retry_count", sa.INTEGER(), nullable=True),
        sa.Column("max_retries", sa.INTEGER(), nullable=True),
        sa.Column("approved_at", sa.DATETIME(), nullable=True),
        sa.Column("approved_by", sa.VARCHAR(length=100), nullable=True),
        sa.Column("edit_count", sa.INTEGER(), nullable=True),
        sa.Column("last_edited_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["follow_up_campaigns.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["email_log_id"], ["email_logs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["step_id"], ["follow_up_steps.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_follow_up_emails_status"), "follow_up_emails", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_follow_up_emails_id"), "follow_up_emails", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_follow_up_emails_campaign_id"),
        "follow_up_emails",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=50), nullable=True),
        sa.Column("personal_email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("linkedin_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("github_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("twitter_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("website_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("portfolio_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("behance_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("dribbble_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("medium_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("stackoverflow_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("other_links", sqlite.JSON(), nullable=True),
        sa.Column("headline", sa.VARCHAR(length=255), nullable=True),
        sa.Column("bio", sa.TEXT(), nullable=True),
        sa.Column("years_experience", sa.INTEGER(), nullable=True),
        sa.Column("current_company", sa.VARCHAR(length=255), nullable=True),
        sa.Column("current_title", sa.VARCHAR(length=255), nullable=True),
        sa.Column("portfolio_projects", sqlite.JSON(), nullable=True),
        sa.Column("achievements", sqlite.JSON(), nullable=True),
        sa.Column("value_propositions", sqlite.JSON(), nullable=True),
        sa.Column("email_signature", sa.TEXT(), nullable=True),
        sa.Column("signature_html", sa.TEXT(), nullable=True),
        sa.Column("preferred_follow_up_tone", sa.VARCHAR(length=12), nullable=True),
        sa.Column("default_sequence_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["default_sequence_id"], ["follow_up_sequences.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id"),
    )
    op.create_index(
        op.f("ix_candidate_profiles_id"), "candidate_profiles", ["id"], unique=False
    )
    op.create_table(
        "domain_reputations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("domain", sa.VARCHAR(length=255), nullable=False),
        sa.Column("email_address", sa.VARCHAR(length=255), nullable=False),
        sa.Column("overall_reputation", sa.FLOAT(), nullable=True),
        sa.Column("spf_configured", sa.BOOLEAN(), nullable=True),
        sa.Column("dkim_configured", sa.BOOLEAN(), nullable=True),
        sa.Column("dmarc_configured", sa.BOOLEAN(), nullable=True),
        sa.Column("authentication_score", sa.FLOAT(), nullable=True),
        sa.Column("is_blacklisted", sa.BOOLEAN(), nullable=True),
        sa.Column("blacklist_sources", sqlite.JSON(), nullable=True),
        sa.Column("last_blacklist_check", sa.DATETIME(), nullable=True),
        sa.Column("total_emails_sent", sa.INTEGER(), nullable=True),
        sa.Column("total_bounces", sa.INTEGER(), nullable=True),
        sa.Column("total_spam_reports", sa.INTEGER(), nullable=True),
        sa.Column("lifetime_delivery_rate", sa.FLOAT(), nullable=True),
        sa.Column("lifetime_bounce_rate", sa.FLOAT(), nullable=True),
        sa.Column("first_email_date", sa.DATETIME(), nullable=True),
        sa.Column("domain_age_days", sa.INTEGER(), nullable=True),
        sa.Column("sending_consistency_score", sa.FLOAT(), nullable=True),
        sa.Column("provider_warnings", sqlite.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domain_reputations_id"), "domain_reputations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_domain_reputations_domain"),
        "domain_reputations",
        ["domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_reputations_candidate_id"),
        "domain_reputations",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "warmup_health_alerts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("alert_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("severity", sa.VARCHAR(length=20), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column("context", sqlite.JSON(), nullable=True),
        sa.Column("recommended_actions", sqlite.JSON(), nullable=True),
        sa.Column("is_read", sa.BOOLEAN(), nullable=True),
        sa.Column("is_resolved", sa.BOOLEAN(), nullable=True),
        sa.Column("resolved_at", sa.DATETIME(), nullable=True),
        sa.Column("resolved_by", sa.VARCHAR(length=100), nullable=True),
        sa.Column("resolution_note", sa.TEXT(), nullable=True),
        sa.Column("auto_resolve_on_improvement", sa.BOOLEAN(), nullable=True),
        sa.Column(
            "triggered_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_warmup_health_alerts_triggered_at"),
        "warmup_health_alerts",
        ["triggered_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warmup_health_alerts_severity"),
        "warmup_health_alerts",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warmup_health_alerts_is_resolved"),
        "warmup_health_alerts",
        ["is_resolved"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warmup_health_alerts_is_read"),
        "warmup_health_alerts",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warmup_health_alerts_id"), "warmup_health_alerts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_warmup_health_alerts_candidate_id"),
        "warmup_health_alerts",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warmup_health_alerts_alert_type"),
        "warmup_health_alerts",
        ["alert_type"],
        unique=False,
    )
    op.create_table(
        "follow_up_sequences",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=8), nullable=True),
        sa.Column("is_system_preset", sa.BOOLEAN(), nullable=True),
        sa.Column("stop_on_reply", sa.BOOLEAN(), nullable=True),
        sa.Column("stop_on_bounce", sa.BOOLEAN(), nullable=True),
        sa.Column("use_threading", sa.BOOLEAN(), nullable=True),
        sa.Column("respect_business_hours", sa.BOOLEAN(), nullable=True),
        sa.Column("business_hours_start", sa.INTEGER(), nullable=True),
        sa.Column("business_hours_end", sa.INTEGER(), nullable=True),
        sa.Column("include_candidate_links", sa.BOOLEAN(), nullable=True),
        sa.Column("include_portfolio", sa.BOOLEAN(), nullable=True),
        sa.Column("include_signature", sa.BOOLEAN(), nullable=True),
        sa.Column("custom_signature", sa.TEXT(), nullable=True),
        sa.Column("preferred_send_hour", sa.INTEGER(), nullable=True),
        sa.Column("preferred_timezone", sa.VARCHAR(length=50), nullable=True),
        sa.Column("times_used", sa.INTEGER(), nullable=True),
        sa.Column("total_campaigns", sa.INTEGER(), nullable=True),
        sa.Column("successful_replies", sa.INTEGER(), nullable=True),
        sa.Column("reply_rate", sa.FLOAT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_follow_up_sequences_id"), "follow_up_sequences", ["id"], unique=False
    )
    op.create_table(
        "follow_up_steps",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("sequence_id", sa.INTEGER(), nullable=False),
        sa.Column("step_number", sa.INTEGER(), nullable=False),
        sa.Column("delay_days", sa.INTEGER(), nullable=False),
        sa.Column("delay_hours", sa.INTEGER(), nullable=True),
        sa.Column("strategy", sa.VARCHAR(length=18), nullable=True),
        sa.Column("tone", sa.VARCHAR(length=12), nullable=True),
        sa.Column("subject_template", sa.VARCHAR(length=500), nullable=True),
        sa.Column("body_template", sa.TEXT(), nullable=False),
        sa.Column("generation_hints", sqlite.JSON(), nullable=True),
        sa.Column("include_original_context", sa.BOOLEAN(), nullable=True),
        sa.Column("include_value_proposition", sa.BOOLEAN(), nullable=True),
        sa.Column("include_portfolio_link", sa.BOOLEAN(), nullable=True),
        sa.Column("include_call_to_action", sa.BOOLEAN(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sequence_id"], ["follow_up_sequences.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sequence_id", "step_number", name=op.f("unique_step_in_sequence")
        ),
    )
    op.create_index(
        op.f("ix_follow_up_steps_sequence_id"),
        "follow_up_steps",
        ["sequence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_follow_up_steps_id"), "follow_up_steps", ["id"], unique=False
    )
    op.create_table(
        "company_projects",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("project_type", sa.VARCHAR(length=11), nullable=True),
        sa.Column("url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("technologies", sqlite.JSON(), nullable=True),
        sa.Column("skills_required", sqlite.JSON(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("discovered_at", sa.DATETIME(), nullable=True),
        sa.Column("last_updated", sa.DATETIME(), nullable=True),
        sa.Column("source_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("confidence_score", sa.FLOAT(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_projects_id"), "company_projects", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_company_projects_company_id"),
        "company_projects",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "follow_up_campaigns",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("sequence_id", sa.INTEGER(), nullable=True),
        sa.Column("application_id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=16), nullable=True),
        sa.Column("is_auto_mode", sa.BOOLEAN(), nullable=True),
        sa.Column("auto_mode_approved", sa.BOOLEAN(), nullable=True),
        sa.Column("auto_mode_approved_at", sa.DATETIME(), nullable=True),
        sa.Column("current_step", sa.INTEGER(), nullable=True),
        sa.Column("total_steps", sa.INTEGER(), nullable=True),
        sa.Column("next_send_date", sa.DATETIME(), nullable=True),
        sa.Column("last_sent_date", sa.DATETIME(), nullable=True),
        sa.Column("original_email_context", sqlite.JSON(), nullable=True),
        sa.Column("company_context", sqlite.JSON(), nullable=True),
        sa.Column("candidate_context", sqlite.JSON(), nullable=True),
        sa.Column("reply_detected", sa.BOOLEAN(), nullable=True),
        sa.Column("reply_detected_at", sa.DATETIME(), nullable=True),
        sa.Column("reply_source", sa.VARCHAR(length=50), nullable=True),
        sa.Column("emails_sent", sa.INTEGER(), nullable=True),
        sa.Column("emails_opened", sa.INTEGER(), nullable=True),
        sa.Column("emails_clicked", sa.INTEGER(), nullable=True),
        sa.Column("user_notes", sa.TEXT(), nullable=True),
        sa.Column("cancellation_reason", sa.VARCHAR(length=500), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"], ["follow_up_sequences.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_follow_up_campaigns_status"),
        "follow_up_campaigns",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_follow_up_campaigns_next_send_date"),
        "follow_up_campaigns",
        ["next_send_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_follow_up_campaigns_id"), "follow_up_campaigns", ["id"], unique=False
    )
    op.create_table(
        "skill_matches",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.INTEGER(), nullable=False),
        sa.Column("project_id", sa.INTEGER(), nullable=True),
        sa.Column("match_strength", sa.VARCHAR(length=8), nullable=True),
        sa.Column("overall_score", sa.FLOAT(), nullable=True),
        sa.Column("matched_skills", sqlite.JSON(), nullable=True),
        sa.Column("candidate_skills_used", sqlite.JSON(), nullable=True),
        sa.Column("company_needs", sqlite.JSON(), nullable=True),
        sa.Column("category_scores", sqlite.JSON(), nullable=True),
        sa.Column("match_context", sa.TEXT(), nullable=True),
        sa.Column("talking_points", sqlite.JSON(), nullable=True),
        sa.Column("calculated_at", sa.DATETIME(), nullable=True),
        sa.Column("expires_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["project_id"], ["company_projects.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_matches_id"), "skill_matches", ["id"], unique=False)
    op.create_index(
        op.f("ix_skill_matches_company_id"),
        "skill_matches",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "candidate_skill_profiles",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("programming_languages", sqlite.JSON(), nullable=True),
        sa.Column("frameworks", sqlite.JSON(), nullable=True),
        sa.Column("databases", sqlite.JSON(), nullable=True),
        sa.Column("cloud_devops", sqlite.JSON(), nullable=True),
        sa.Column("tools", sqlite.JSON(), nullable=True),
        sa.Column("soft_skills", sqlite.JSON(), nullable=True),
        sa.Column("domain_knowledge", sqlite.JSON(), nullable=True),
        sa.Column("projects", sqlite.JSON(), nullable=True),
        sa.Column("work_experience", sqlite.JSON(), nullable=True),
        sa.Column("education", sqlite.JSON(), nullable=True),
        sa.Column("achievements", sqlite.JSON(), nullable=True),
        sa.Column("certifications", sqlite.JSON(), nullable=True),
        sa.Column("skill_levels", sqlite.JSON(), nullable=True),
        sa.Column("primary_expertise", sqlite.JSON(), nullable=True),
        sa.Column("secondary_skills", sqlite.JSON(), nullable=True),
        sa.Column("years_experience", sa.FLOAT(), nullable=True),
        sa.Column("completeness_score", sa.FLOAT(), nullable=True),
        sa.Column("last_analyzed", sa.DATETIME(), nullable=True),
        sa.Column("source_resume_id", sa.INTEGER(), nullable=True),
        sa.Column("extraction_method", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id"),
    )
    op.create_index(
        op.f("ix_candidate_skill_profiles_id"),
        "candidate_skill_profiles",
        ["id"],
        unique=False,
    )
    op.create_table(
        "personalized_email_drafts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.INTEGER(), nullable=False),
        sa.Column("skill_match_id", sa.INTEGER(), nullable=True),
        sa.Column("subject_line", sa.VARCHAR(length=255), nullable=False),
        sa.Column("subject_alternatives", sqlite.JSON(), nullable=True),
        sa.Column("email_body", sa.TEXT(), nullable=False),
        sa.Column("email_html", sa.TEXT(), nullable=True),
        sa.Column("opening", sa.TEXT(), nullable=True),
        sa.Column("skill_highlights", sa.TEXT(), nullable=True),
        sa.Column("company_specific", sa.TEXT(), nullable=True),
        sa.Column("call_to_action", sa.TEXT(), nullable=True),
        sa.Column("closing", sa.TEXT(), nullable=True),
        sa.Column("tone", sa.VARCHAR(length=12), nullable=True),
        sa.Column("personalization_level", sa.FLOAT(), nullable=True),
        sa.Column("confidence_score", sa.FLOAT(), nullable=True),
        sa.Column("relevance_score", sa.FLOAT(), nullable=True),
        sa.Column("is_favorite", sa.BOOLEAN(), nullable=True),
        sa.Column("is_used", sa.BOOLEAN(), nullable=True),
        sa.Column("used_at", sa.DATETIME(), nullable=True),
        sa.Column("generation_params", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["skill_match_id"], ["skill_matches.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personalized_email_drafts_id"),
        "personalized_email_drafts",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personalized_email_drafts_company_id"),
        "personalized_email_drafts",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "ab_test_variants",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("test_id", sa.INTEGER(), nullable=False),
        sa.Column("sequence_id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("is_control", sa.BOOLEAN(), nullable=True),
        sa.Column("allocation_weight", sa.FLOAT(), nullable=True),
        sa.Column("total_campaigns", sa.INTEGER(), nullable=True),
        sa.Column("total_emails_sent", sa.INTEGER(), nullable=True),
        sa.Column("total_opens", sa.INTEGER(), nullable=True),
        sa.Column("total_clicks", sa.INTEGER(), nullable=True),
        sa.Column("total_replies", sa.INTEGER(), nullable=True),
        sa.Column("open_rate", sa.FLOAT(), nullable=True),
        sa.Column("click_rate", sa.FLOAT(), nullable=True),
        sa.Column("reply_rate", sa.FLOAT(), nullable=True),
        sa.Column("avg_time_to_reply_hours", sa.FLOAT(), nullable=True),
        sa.Column("avg_emails_to_reply", sa.FLOAT(), nullable=True),
        sa.Column("conversion_rate", sa.FLOAT(), nullable=True),
        sa.Column("std_error", sa.FLOAT(), nullable=True),
        sa.Column("confidence_interval_lower", sa.FLOAT(), nullable=True),
        sa.Column("confidence_interval_upper", sa.FLOAT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sequence_id"], ["follow_up_sequences.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["test_id"], ["ab_tests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ab_test_variants_test_id"),
        "ab_test_variants",
        ["test_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ab_test_variants_id"), "ab_test_variants", ["id"], unique=False
    )
    op.create_table(
        "warmup_milestones",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("milestone_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("achievement_data", sqlite.JSON(), nullable=True),
        sa.Column("badge_icon", sa.VARCHAR(length=50), nullable=True),
        sa.Column("badge_color", sa.VARCHAR(length=20), nullable=True),
        sa.Column(
            "achieved_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_warmup_milestones_id"), "warmup_milestones", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_warmup_milestones_candidate_id"),
        "warmup_milestones",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "company_research_cache",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.INTEGER(), nullable=False),
        sa.Column("research_depth", sa.VARCHAR(length=10), nullable=True),
        sa.Column("about_summary", sa.TEXT(), nullable=True),
        sa.Column("mission_statement", sa.TEXT(), nullable=True),
        sa.Column("company_culture", sqlite.JSON(), nullable=True),
        sa.Column("recent_news", sqlite.JSON(), nullable=True),
        sa.Column("job_openings", sqlite.JSON(), nullable=True),
        sa.Column("key_people", sqlite.JSON(), nullable=True),
        sa.Column("funding_info", sqlite.JSON(), nullable=True),
        sa.Column("competitors", sqlite.JSON(), nullable=True),
        sa.Column("tech_stack_detailed", sqlite.JSON(), nullable=True),
        sa.Column("github_repos", sqlite.JSON(), nullable=True),
        sa.Column("blog_posts", sqlite.JSON(), nullable=True),
        sa.Column("patents", sqlite.JSON(), nullable=True),
        sa.Column("social_links", sqlite.JSON(), nullable=True),
        sa.Column("employee_count_estimate", sa.INTEGER(), nullable=True),
        sa.Column("growth_signals", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("expires_at", sa.DATETIME(), nullable=True),
        sa.Column("last_refreshed", sa.DATETIME(), nullable=True),
        sa.Column("completeness_score", sa.FLOAT(), nullable=True),
        sa.Column("data_sources", sqlite.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_research_cache_id"),
        "company_research_cache",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_research_cache_company_id"),
        "company_research_cache",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "follow_up_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("campaign_id", sa.INTEGER(), nullable=False),
        sa.Column("action", sa.VARCHAR(length=100), nullable=False),
        sa.Column("step_number", sa.INTEGER(), nullable=True),
        sa.Column("details", sqlite.JSON(), nullable=True),
        sa.Column("actor", sa.VARCHAR(length=100), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["follow_up_campaigns.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_follow_up_logs_id"), "follow_up_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_follow_up_logs_campaign_id"),
        "follow_up_logs",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "warmup_health_scores",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("score_date", sa.DATETIME(), nullable=False),
        sa.Column("overall_score", sa.FLOAT(), nullable=False),
        sa.Column("health_status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("delivery_score", sa.FLOAT(), nullable=True),
        sa.Column("bounce_score", sa.FLOAT(), nullable=True),
        sa.Column("open_score", sa.FLOAT(), nullable=True),
        sa.Column("spam_score", sa.FLOAT(), nullable=True),
        sa.Column("consistency_score", sa.FLOAT(), nullable=True),
        sa.Column("delivery_rate", sa.FLOAT(), nullable=True),
        sa.Column("bounce_rate", sa.FLOAT(), nullable=True),
        sa.Column("open_rate", sa.FLOAT(), nullable=True),
        sa.Column("spam_rate", sa.FLOAT(), nullable=True),
        sa.Column("click_rate", sa.FLOAT(), nullable=True),
        sa.Column("emails_sent", sa.INTEGER(), nullable=True),
        sa.Column("emails_delivered", sa.INTEGER(), nullable=True),
        sa.Column("emails_bounced", sa.INTEGER(), nullable=True),
        sa.Column("emails_opened", sa.INTEGER(), nullable=True),
        sa.Column("spam_complaints", sa.INTEGER(), nullable=True),
        sa.Column("score_trend", sa.INTEGER(), nullable=True),
        sa.Column("delivery_trend", sa.INTEGER(), nullable=True),
        sa.Column("bounce_trend", sa.INTEGER(), nullable=True),
        sa.Column("avg_7day_score", sa.FLOAT(), nullable=True),
        sa.Column("avg_7day_delivery", sa.FLOAT(), nullable=True),
        sa.Column("avg_7day_bounce", sa.FLOAT(), nullable=True),
        sa.Column("recommendations", sqlite.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_warmup_health_scores_score_date"),
        "warmup_health_scores",
        ["score_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warmup_health_scores_id"), "warmup_health_scores", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_warmup_health_scores_candidate_id"),
        "warmup_health_scores",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "ab_tests",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("hypothesis", sa.TEXT(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=15), nullable=True),
        sa.Column("allocation_strategy", sa.VARCHAR(length=50), nullable=True),
        sa.Column("minimum_sample_size", sa.INTEGER(), nullable=True),
        sa.Column("confidence_level", sa.FLOAT(), nullable=True),
        sa.Column("primary_metric", sa.VARCHAR(length=50), nullable=True),
        sa.Column("secondary_metrics", sqlite.JSON(), nullable=True),
        sa.Column("winner_variant_id", sa.INTEGER(), nullable=True),
        sa.Column("winner_selected_at", sa.DATETIME(), nullable=True),
        sa.Column("winner_selection_method", sa.VARCHAR(length=50), nullable=True),
        sa.Column("total_campaigns", sa.INTEGER(), nullable=True),
        sa.Column("statistical_significance", sa.FLOAT(), nullable=True),
        sa.Column("confidence_interval", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["winner_variant_id"], ["ab_test_variants.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ab_tests_status"), "ab_tests", ["status"], unique=False)
    op.create_index(op.f("ix_ab_tests_id"), "ab_tests", ["id"], unique=False)
    op.drop_index(op.f("ix_extraction_results_job_id"), table_name="extraction_results")
    op.drop_index(op.f("ix_extraction_results_id"), table_name="extraction_results")
    op.drop_table("extraction_results")
    op.drop_index(
        op.f("ix_extraction_progress_job_id"), table_name="extraction_progress"
    )
    op.drop_index(op.f("ix_extraction_progress_id"), table_name="extraction_progress")
    op.drop_index(
        op.f("ix_extraction_progress_created_at"), table_name="extraction_progress"
    )
    op.drop_table("extraction_progress")
    op.drop_index(op.f("ix_extraction_templates_id"), table_name="extraction_templates")
    op.drop_index(
        op.f("ix_extraction_templates_candidate_id"), table_name="extraction_templates"
    )
    op.drop_table("extraction_templates")
    op.drop_index(op.f("ix_extraction_jobs_status"), table_name="extraction_jobs")
    op.drop_index(op.f("ix_extraction_jobs_sector"), table_name="extraction_jobs")
    op.drop_index(op.f("ix_extraction_jobs_id"), table_name="extraction_jobs")
    op.drop_index(op.f("ix_extraction_jobs_candidate_id"), table_name="extraction_jobs")
    op.drop_table("extraction_jobs")
    # ### end Alembic commands ###
