"""Add i18n support, resume versions, email templates, and follow-up features

Revision ID: 585794b66272
Revises: 9ef8048c4be3
Create Date: 2025-12-31 12:56:21.242535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "585794b66272"
down_revision: Union[str, Sequence[str], None] = "9ef8048c4be3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "INITIAL_APPLICATION",
                "FOLLOW_UP",
                "THANK_YOU",
                "INQUIRY",
                "NETWORKING",
                "REFERRAL",
                "REAPPLICATION",
                name="templatecategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum(
                "ENGLISH",
                "HINDI",
                "SPANISH",
                "FRENCH",
                "GERMAN",
                "CHINESE",
                "JAPANESE",
                "KOREAN",
                name="emaillanguage",
            ),
            nullable=False,
        ),
        sa.Column("subject_template", sa.String(length=500), nullable=False),
        sa.Column("body_template_html", sa.Text(), nullable=False),
        sa.Column("body_template_text", sa.Text(), nullable=True),
        sa.Column("target_position", sa.String(length=255), nullable=True),
        sa.Column("target_industry", sa.String(length=255), nullable=True),
        sa.Column("target_country", sa.String(length=100), nullable=True),
        sa.Column("target_company_size", sa.String(length=50), nullable=True),
        sa.Column("available_variables", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("times_used", sa.Integer(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_templates_candidate_id"),
        "email_templates",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_templates_category"),
        "email_templates",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_templates_deleted_at"),
        "email_templates",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_templates_id"), "email_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_email_templates_language"),
        "email_templates",
        ["language"],
        unique=False,
    )
    op.create_table(
        "resume_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "language",
            sa.Enum(
                "ENGLISH",
                "HINDI",
                "SPANISH",
                "FRENCH",
                "GERMAN",
                "CHINESE",
                "JAPANESE",
                "KOREAN",
                name="resumelanguage",
            ),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("target_position", sa.String(length=255), nullable=True),
        sa.Column("target_industry", sa.String(length=255), nullable=True),
        sa.Column("target_country", sa.String(length=100), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("times_used", sa.Integer(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_versions_candidate_id"),
        "resume_versions",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_versions_deleted_at"),
        "resume_versions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_versions_id"), "resume_versions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_resume_versions_language"),
        "resume_versions",
        ["language"],
        unique=False,
    )
    # Use batch mode for SQLite compatibility when altering existing table
    with op.batch_alter_table("applications") as batch_op:
        batch_op.add_column(sa.Column("resume_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("email_template_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("parent_application_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "application_type",
                sa.Enum(
                    "INITIAL",
                    "FOLLOW_UP",
                    "REAPPLICATION",
                    "REFERRAL",
                    name="applicationtype",
                ),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("recruiter_country", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("recruiter_language", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("position_country", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("position_language", sa.String(length=50), nullable=True)
        )

        batch_op.create_index("ix_applications_application_type", ["application_type"])
        batch_op.create_index(
            "ix_applications_email_template_id", ["email_template_id"]
        )
        batch_op.create_index(
            "ix_applications_parent_application_id", ["parent_application_id"]
        )
        batch_op.create_index("ix_applications_position_country", ["position_country"])
        batch_op.create_index(
            "ix_applications_resume_version_id", ["resume_version_id"]
        )

        batch_op.create_foreign_key(
            "fk_applications_resume_version_id",
            "resume_versions",
            ["resume_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_applications_email_template_id",
            "email_templates",
            ["email_template_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_applications_parent_application_id",
            "applications",
            ["parent_application_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.add_column(
        "companies",
        sa.Column("headquarters_country", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("headquarters_city", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("primary_language", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_companies_headquarters_country"),
        "companies",
        ["headquarters_country"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_headquarters_country"), table_name="companies")
    op.drop_column("companies", "primary_language")
    op.drop_column("companies", "headquarters_city")
    op.drop_column("companies", "headquarters_country")

    with op.batch_alter_table("applications") as batch_op:
        batch_op.drop_constraint(
            "fk_applications_resume_version_id", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_applications_email_template_id", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_applications_parent_application_id", type_="foreignkey"
        )

        batch_op.drop_index("ix_applications_resume_version_id")
        batch_op.drop_index("ix_applications_position_country")
        batch_op.drop_index("ix_applications_parent_application_id")
        batch_op.drop_index("ix_applications_email_template_id")
        batch_op.drop_index("ix_applications_application_type")

        batch_op.drop_column("position_language")
        batch_op.drop_column("position_country")
        batch_op.drop_column("recruiter_language")
        batch_op.drop_column("recruiter_country")
        batch_op.drop_column("application_type")
        batch_op.drop_column("parent_application_id")
        batch_op.drop_column("email_template_id")
        batch_op.drop_column("resume_version_id")
    op.drop_index(op.f("ix_resume_versions_language"), table_name="resume_versions")
    op.drop_index(op.f("ix_resume_versions_id"), table_name="resume_versions")
    op.drop_index(op.f("ix_resume_versions_deleted_at"), table_name="resume_versions")
    op.drop_index(op.f("ix_resume_versions_candidate_id"), table_name="resume_versions")
    op.drop_table("resume_versions")
    op.drop_index(op.f("ix_email_templates_language"), table_name="email_templates")
    op.drop_index(op.f("ix_email_templates_id"), table_name="email_templates")
    op.drop_index(op.f("ix_email_templates_deleted_at"), table_name="email_templates")
    op.drop_index(op.f("ix_email_templates_category"), table_name="email_templates")
    op.drop_index(op.f("ix_email_templates_candidate_id"), table_name="email_templates")
    op.drop_table("email_templates")
    # ### end Alembic commands ###
