"""Initial schema with soft delete and user roles

Revision ID: 9ef8048c4be3
Revises: 
Create Date: 2025-12-31 12:35:41.853741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef8048c4be3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PRAGYA', 'ANIRUDDH', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('email_account', sa.String(length=255), nullable=False),
    sa.Column('email_password', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('total_applications_sent', sa.Integer(), nullable=True),
    sa.Column('total_responses_received', sa.Integer(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_deleted_at'), 'candidates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_role'), 'candidates', ['role'], unique=False)
    op.create_index(op.f('ix_candidates_username'), 'candidates', ['username'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('careers_url', sa.String(length=500), nullable=True),
    sa.Column('alignment_pragya_text', sa.Text(), nullable=True),
    sa.Column('alignment_pragya_score', sa.Float(), nullable=True),
    sa.Column('alignment_aniruddh_text', sa.Text(), nullable=True),
    sa.Column('alignment_aniruddh_score', sa.Float(), nullable=True),
    sa.Column('job_postings_pragya', sa.JSON(), nullable=True),
    sa.Column('job_postings_aniruddh', sa.JSON(), nullable=True),
    sa.Column('last_researched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('research_source', sa.String(length=100), nullable=True),
    sa.Column('total_applications', sa.Integer(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_deleted_at'), 'companies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_email', sa.String(length=255), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('position_level', sa.String(length=50), nullable=True),
    sa.Column('job_posting_url', sa.String(length=500), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_body_html', sa.Text(), nullable=True),
    sa.Column('alignment_text', sa.Text(), nullable=True),
    sa.Column('alignment_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'OPENED', 'REPLIED', 'INTERVIEW', 'REJECTED', 'ACCEPTED', name='applicationstatusenum'), nullable=True),
    sa.Column('tracking_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_company_id'), 'applications', ['company_id'], unique=False)
    op.create_index(op.f('ix_applications_deleted_at'), 'applications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_recruiter_email'), 'applications', ['recruiter_email'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_tracking_id'), 'applications', ['tracking_id'], unique=True)
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_application_id'), 'email_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_email_logs_candidate_id'), 'email_logs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_email_logs_deleted_at'), 'email_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_deleted_at'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_candidate_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_application_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_applications_tracking_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_recruiter_email'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_deleted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_company_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_deleted_at'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_candidates_username'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_role'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_deleted_at'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
